definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/productfacet:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:template: productfacetpage-main
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: productfacet/main
