definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/productdetails-page:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:componentclassname: com.kohler.commons.components.ProductDetailsComponent
        hst:template: productdetails-main
