definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/productscompare-page:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:componentclassname: com.kohler.commons.components.CompareProductsComponent
        hst:template: productscompare-main
