definitions:
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
    /hippo:configuration/hippo:translations:
      /hippo:types:
        jcr:primaryType: hipposys:resourcebundles
    /hippo:configuration/hippo:groups/webmaster:
      hipposys:members:
        operation: add
        type: string
        value: [editor]
    
