definitions:
  config:
    /hst:hst/hst:configurations/common/hst:components/productSitemap:
      jcr:primaryType: hst:component
      hst:componentclassname: com.kohler.commons.components.ProductSitemapComponent
      hst:template: specific-sitemap.ftl
